### ISSUE TITLE
[EPIC] Consumer CLI user journey

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-portal-content#8]
User journey for 

 - [ ] How to find data
 - [ ] How to download
 - [ ] How to subscribe to change notifications

**Comment by theathorn** [comment]
All issues resolved.
